# Generated by Django 4.2 on 2023-06-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeeledger',
            index=models.Index(fields=['id'], name='ledger_app__id_ce1648_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeledger',
            index=models.Index(fields=['employee'], name='ledger_app__employe_cd1e76_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeledger',
            index=models.Index(fields=['title', 'body'], name='ledger_app__title_8a4eb8_idx'),
        ),
    ]
