# Generated by Django 4.2 on 2023-06-10 20:05

import banking_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0002_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=banking_app.utils.account_number_generator, editable=False, unique=True),
        ),
    ]
