# Generated by Django 4.2 on 2023-06-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0003_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Savings', 'Savings'), ('Current', 'Current'), ('Loan', 'Loan'), ('Credit', 'Credit')], max_length=16),
        ),
    ]
