# Generated by Django 4.2 on 2023-06-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0004_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Cash Deposit', 'Cash Deposit'), ('Account Transfer', 'Account Transfer'), ('Account Withdrawal', 'Account Withdrawal')], max_length=128),
        ),
    ]
