# Generated by Django 4.2 on 2023-06-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_app', '0006_transaction_authorised_by'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['id'], name='banking_app_id_5f06b1_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_number'], name='banking_app_account_8b7490_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['id'], name='banking_app_id_bfda22_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['destination', 'source'], name='banking_app_destina_87c8fa_idx'),
        ),
    ]
