# Generated by Django 4.2 on 2023-06-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='regnal_suffix',
            field=models.CharField(blank=True, help_text='I, II, Jr., Sr., etc', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='knowyourcustomer',
            name='address_proof_value',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='knowyourcustomer',
            name='id_proof_value',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='kycdocuments',
            name='address_proof_type',
            field=models.CharField(blank=True, choices=[('Aadhar Card', 'Aadhar Card'), ('Voter ID', 'Voter ID'), ('Electricity Bill', 'Electricity Bill'), ('Passport', 'Passport'), ('Driving License', 'Driving License')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='kycdocuments',
            name='id_proof_type',
            field=models.CharField(blank=True, choices=[('PAN Card', 'PAN Card'), ('Aadhar Card', 'Aadhar Card'), ('Voter ID', 'Voter ID'), ('Passport', 'Passport'), ('Driving License', 'Driving License')], max_length=25, null=True),
        ),
    ]
