# Generated by Django 4.2 on 2023-06-18 00:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app', '0002_alter_customer_gender_alter_customer_regnal_suffix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocuments',
            name='address_proof',
            field=models.ImageField(blank=True, null=True, upload_to='custdocuments/address_proof', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'png'))]),
        ),
        migrations.AlterField(
            model_name='kycdocuments',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='custdocuments/id_proof', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'png'))]),
        ),
        migrations.AlterField(
            model_name='kycdocuments',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='custdocuments/photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg', 'png'))]),
        ),
    ]
