# Generated by Django 4.2 on 2023-06-25 02:39

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app', '0004_customer_kyc_app_cus_id_ef9be8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, validators=[django.core.validators.EmailValidator(message='The email address is invalid.')]),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='The phone number is invalid.', regex=re.compile('^[6-9]{1}[0-9]{9}$'))]),
        ),
    ]
