# Generated by Django 4.2 on 2023-06-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app', '0005_customer_email_customer_phone'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='kyc_app_cus_email_5fca7d_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='kyc_app_cus_phone_d34e67_idx'),
        ),
    ]
