# Generated by Django 4.2 on 2023-06-25 02:42

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app', '0006_customer_kyc_app_cus_email_5fca7d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='The phone number is invalid.', regex=re.compile('^(\\+[1-9]{1-3})?[6-9]{1}[0-9]{9}$'))]),
        ),
    ]
