# Generated by Django 4.2 on 2023-06-25 03:00

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_app', '0009_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=64, unique=True, validators=[django.core.validators.EmailValidator(message='The email address is invalid.')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='The phone number is invalid.', regex=re.compile('^(\\+[0-9]{1,3})?([\\s.-])?(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?([\\s.-])?\\d{3}([\\s.-])?\\d{4}$'))]),
        ),
    ]
