# Generated by Django 4.2 on 2023-06-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_address_proof_user_id_proof_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Accountant', 'Accountant'), ('Teller', 'Teller'), ('Administrator', 'Administrator'), ('Moderator', 'Moderator')], default='Teller', max_length=128),
        ),
    ]
