# Generated by Django 4.2 on 2023-06-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
